### ISSUE TITLE
Thanks / Badge issue

### ISSUE THREAD

**Issue by tymondesigns** [beerpay/beerpay.io#10]
Hello there,

Firstly thank you for this great project! I think it certainly has the potential to overtake Gratipay as the leading open-source support service.

One issue I would like to raise is when adding a new project, if I untick "Add beerpay badge" then it goes ahead and adds it anyway.

Cheers

**Comment by cag1982** [comment]
I saw the same problem, I just added a wish for this bug on beerpay!

https://beerpay.io/beerpay/beerpay.io/wishes?sort=newest&page=1

**Comment by colkito** [comment]
Thanks @tymondesigns, @cag1982!
I just fixed this bug!
🍻

**Comment by tymondesigns** [comment]
👍
