### ISSUE TITLE
Renaming the repository

### ISSUE THREAD

**Issue by otanim** [beerpay/beerpay.io#18]
Hello dear Beerpay team, since I've renamed my https://github.com/LinguaCode/core project from **linguacode-api** to **core**, I would like to change this information in Beerpay.
Can you please help me to solve this issue ?

Sincerely,
Arman

**Comment by colkito** [comment]
Hi @otanim!
Now you can edit your project name and their GitHub URL.
Thanks for your feedback.

🍻 Cheers!

**Comment by otanim** [comment]
Hi @colkito!
Thanks to enable renaming the repository's name, but after renaming unfortunately  I get "An error has occurred." error message:
![image](https://cloud.githubusercontent.com/assets/7108843/16914423/d492e31e-4d02-11e6-8a81-35e0a53c52d4.png)

**Comment by colkito** [comment]
Ok, it must be solved.
Please, try again @otanim!

**Comment by otanim** [comment]
@colkito everything works fine !
Thanks !

**Comment by otanim** [comment]
@colkito I'm so sorry but I've renamed the project to "LinguaCode/core" and the page was crushed..
Seems need to parse the name of the project, for ex. "LinguaCode/core" will be "linguacode-core" in address bar.

**Comment by colkito** [comment]
@otanim If you see the LinguaCode page (https://beerpay.io/LinguaCode), your project is redirecting to https://beerpay.io/LinguaCode/LinguaCode/core 
That is right? (double **/LinguaCode**)
The Beerpay's URLs are thinked to replace **github.com** with **beerpay.io** to keep the namespace for projects.
Please, let me know if your changes are OK.

**Comment by otanim** [comment]
Yeah, actually I should not rename the exist name to "LinguaCode/core" instead of "core".
Seems renaming of the project name must be validated in Beerpay's both for client and server side to prevent this issue.

**Comment by colkito** [comment]
We updated your project on beerpay to **core** and we added new validations for project name.
thanks @otanim!

🍻 Cheers!

**Comment by otanim** [comment]
@colkito now I feel really bad... I've again broke the link... I though that you have resolved issue with "**/**" symbol.. now I've renamed the name of the branch to **core/anothertry**, now it's again doesn't work. I'm sorry.

**Comment by colkito** [comment]
no problem @otanim!
just one question, whats is the final name for your project on Beerpay?
please, note that should be the same name used on GitHub.
Remember, beerpay wants to keep the namespaces from GitHub.

**Comment by otanim** [comment]
@colkito actually I want to keep the name **core**. I've make this change to make sure that the bug is was fixed.

**Comment by colkito** [comment]
great!
yes, this change took a few minutes to impact on the server.
Now it's fixed! and your project was renamed successfully.
Please, let me know if is ok.

thanks @otanim!
🍻

**Comment by otanim** [comment]
@colkito your welcome, can I know test the renaming the name of the project into a incorrect versions ?
