### ISSUE TITLE
Integration with bitbucket

### ISSUE THREAD

**Issue by nolazybits** [beerpay/beerpay.io#19]
Hello there,

First of all thank you much for creating BeerPay.

I just signed up a couple of days ago and noticed that you can only add project from github.
Sadly I have moved (most of) my projects to bitbucket for some times now and I would like to add some of them sitting at bitbucket to BeerPay.

Any thoughts?

Thanks again

**Comment by chebyte** [comment]
Hello @nolazybits  thanks for using Beerpay!, we are getting support for this one soon!.
