### ISSUE TITLE
Missing repo

### ISSUE THREAD

**Issue by jaumard** [beerpay/beerpay.io#20]
Currently I can't see some of my repos, I know fork are not showed (even if some are full rewrite and can be added for beer support lol) but there some repo that are not fork and I can't see them.

Here are some example I can't see on beerpay : 
https://github.com/jaumard/trailpack-twilio
https://github.com/jaumard/trailpack-lob
https://github.com/jaumard/trailpack-passport

Any idea why ? 

Thanks :)

**Comment by colkito** [comment]
Hi @jaumard, could you try again?
It must be solved.

🍻 Cheers!

**Comment by jaumard** [comment]
Hi @colkito ! I just try but no luck :( I try to logout and login again but those repo are missing 
<img width="1251" alt="capture d ecran 2016-08-05 a 17 45 34" src="https://cloud.githubusercontent.com/assets/2970449/17442107/748f32a2-5b34-11e6-8567-26eeaf4cc5ce.png">

**Comment by colkito** [comment]
🤔  we are taking your public repos form the GitHub API (https://api.github.com/users/jaumard/repos?per_page=500)

1. could you check if your projects are listed on that url?
2. try refreshing your page please

**Comment by jaumard** [comment]
Ho now all is ok :) project are under beerpay and the link you provide :) maybe when I try some cache append... 

Thanks ! 
🍻 Cheers!

**Comment by colkito** [comment]
Great!
Thanks for your feedback and patient.

🍻  Cheers!
