### ISSUE TITLE
Do extension for beerpay & github on chrome

### ISSUE THREAD

**Issue by chebyte** [beerpay/beerpay.io#21]
will be nice can use some extension, for support projects on github directly from browser

**Comment by cag1982** [comment]
Now you can support this Wish from https://beerpay.io/beerpay/beerpay.io/wishes/57c9a5bd58bb2e287854c786

🍻 Cheers!

**Comment by cag1982** [comment]
Wish granted successfully on Beerpay! https://beerpay.io/beerpay/beerpay.io/wishes/57c9a5bd58bb2e287854c786
This issue will be closed.

🍻 Cheers!
