### ISSUE TITLE
How do I add a project?!?!?

### ISSUE THREAD

**Issue by cotejp** [beerpay/beerpay.io#26]
- I'm on this page: https://beerpay.io/dashboard/projects/add
- I click on one of my projects. It takes me to GitHub.
- How am I supposed to add a project ?!

**Comment by cotejp** [comment]
One of my project has a long synopsis which pushed the "Add repo" button off the screen to the right. This is why I couldn't figure out how to add a project. You probably should wrap the project synopsis so this isn't an issue.

Thanks.

**Comment by colkito** [comment]
Hi @cotejp 
Yes, is an UI issue.
We will fix that.

Thanks for your feedback
🍻 Cheers!
