### ISSUE TITLE
Grammer error on homepage

### ISSUE THREAD

**Issue by blakethepatton** [beerpay/beerpay.io#27]
There's a pretty simple gramatical error on the beerpay.io homepage. Just missing an s.

It says:

> Free like the Sun
> Beerpay is a free service for any developer who _**want**_ to be free.

Should say: 

> Free like the Sun
> Beerpay is a free service for any developer who _**wants**_ to be free.

**Comment by colkito** [comment]
thanks for report this @blakethepatton.
fixed! 💪
