### ISSUE TITLE
Support for currencies other than USD

### ISSUE THREAD

**Issue by svoop** [beerpay/beerpay.io#3]
USD-only is quite limiting at the moment due to conversion losses when Stripe pays out to non-USD bank accounts.

**Comment by colkito** [comment]
Hi @svoop!
For the moment we won’t be receiving payment in another currency. Stripe handles the conversion for you to receive your payments on your local currency.
For more info about Stripe’s conversions, you can check  this link: https://support.stripe.com/questions/which-currencies-does-stripe-support

Thanks!

**Comment by svoop** [comment]
Hmmm, 3% for beerpay, 2.9% for Stripe... and ?% USD2EUR conversion loss – I'm afraid that's too much for me.

**Comment by colkito** [comment]
Well, in fact you will be earning 92% of each transaction (2% USD2EUR).

**Comment by chebyte** [comment]
@svoop hi, now https://beerpay.io is for free until jan 17, good time for test how works!, try it!
