### ISSUE TITLE
It's not possible to edit a project

### ISSUE THREAD

**Issue by dypsilon** [beerpay/beerpay.io#9]
Hi beerpay team,

right now it's not possible to edit the project information. After clicking on "save" there is a message about some weird error.

Cheers.

![edit](https://cloud.githubusercontent.com/assets/425735/15450873/9e825992-1faa-11e6-8708-a9f579b516ac.png)

**Comment by chebyte** [comment]
@dypsilon thanks for the report!. we are working on that right now! thanks

**Comment by colkito** [comment]
Thanks @dypsilon!
I just fixed this bug!
🍻
